# Site settings
title: Sally Akuffo
description: A website that gives a view of my projects to employers and aspiring Data Scientists
keywords: Data Science
author: Sally Akuffo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
